### ISSUE TITLE
Bug: Application process requests evidence of past salary

### ISSUE THREAD

**Issue by waldoj** [18F/joining-18f#1]
As a part of the process of joining 18F, applicants are required to submit evidence, in the form of W-2s or 1099s, of the past two years' salary. This is a bug in the process. Minorities within the technology industry (which is to say, nearly anybody who isn't a white, cisgender male) are underpaid. Basing 18F salaries on prior salaries perpetuates this discrimination. For this reason, past salaries should not be requested—or, at least, not _required_—for applicants.

**Comment by udoewa** [comment]
Agreed. A very real problem.

**Comment by fureigh** [comment]
@waldoj Thank you for sharing these important concerns! I'm told @jamiealbrecht reached out to you separately, but for anyone else who's watching: the process has changed such that this is no longer the case. Applicants now self-select the GS level to which they're applying.

**Comment by waldoj** [comment]
Yay! I'm happy to hear it. :)

**Comment by fureigh** [comment]
:)
