### ISSUE TITLE
Join 18F Application: Add new essay

### ISSUE THREAD

**Issue by pixelwake** [18F/joining-18f#101]
**Change:** Add a new essay to the application that will allow us to capture the applicants interest in a particular role or team at 18F in addition to serving as a writing sample.

Proposed Question: What role or team at 18F do you believe you are the best fit for and that most excites you? Why?

Additional language to be included with the question: If you need inspiration, check out this page (link to the new page with the roles). If you don't see a perfect role there, that's ok! Just tell us what you think could be

**Comment by fureigh** [comment]
@rooneywp What's the intended end of that last sentence?

**Comment by pixelwake** [comment]
@fureigh It was only intended to encourage the applicant to provide their own suggestion in case they didn't see an exact role. Didn't want them opting out just because there wasn't a match. It needs revised for sure and if it's too confusing we can drop it.

**Comment by fureigh** [comment]
@rooneywp I shortened the last sentence to "Just tell us what you think."

**Comment by pixelwake** [comment]
:+1:
