### ISSUE TITLE
Interviewing rubric is currently engineering-specific

### ISSUE THREAD

**Issue by fureigh** [18F/joining-18f#105]
**Current behavior:**
The rubric on the [interview process](https://pages.18f.gov/joining-18f/interview-process/) page is specific to engineering. It used to be coupled with the interview format on the [engineering interviews](https://pages.18f.gov/joining-18f/interview-process/interviews/engineering-team/) page, which is now more minimal. Perhaps someone split them up?

**Desired behavior:**
- The interview process page accurately reflects the interview process all candidates can expect
- The engineering interviews page accurately reflects the interview process engineering candidates can expect

**Outstanding questions:**
- Does the current description match up with the current performance profile direction/evaluation criteria? —@jamiealbrecht
- Is this how candidates are evaluated? (or, How are candidates evaluated?)

Hat tip to @kaitlin for reporting this.

**Comment by pixelwake** [comment]
Interim solution is in #121

**Comment by kaitlin** [comment]
We specifically added this information to make our interviews more accessible for diverse candidates. We want everyone to come in to the interview knowing what to expect and how to put their best foot forward. It helps prevent hiring for confidence instead of skill.

**Comment by fureigh** [comment]
Noting that @rooneywp restored the list in #121 and that follow-up should include moving the engineering-specific rubric back to the engineering interview page.

**Comment by coreycaitlin** [comment]
We removed this from the general interview process guidance in the move to the new, integrated [Join 18F page](https://18f.gsa.gov/join/#the-interview-process), and all position-specific guidance will be included in individual postings.
