### ISSUE TITLE
Rework inclusion of USDS

### ISSUE THREAD

**Issue by fureigh** [18F/joining-18f#107]

**Comment by pixelwake** [comment]
Interim solution in PR #120

**Comment by pixelwake** [comment]
#122 Capturing this issue here.

In addition to the reworked language describing the coalition, we need to modify the referral code to ensure clarity.

**Comment by pixelwake** [comment]
@fureigh Should we close this issue? We have addressed the primary concerns and we are comfortable with the current state of USDS representation on our site.

**Comment by fureigh** [comment]
@rooneywp Looks like @kimballce's [initial comment](https://github.com/18F/joining-18f/pull/122#issue-117644771) hasn't been addressed. Want to add that referral code to the USDS section of [Roles and teams](https://github.com/18F/joining-18f/blob/534fc9748d84e313b54d3698cb60c9b63a85ba45/pages/roles-and-teams.md)?

**Comment by pixelwake** [comment]
@fureigh We can put it there but I'm not clear on what insight we are looking for by having USDS track that code. I'd almost rather not include it on the site, so that there isn't any confusion when we actually refer people to apply to USDS. What do you think?

**Comment by kimballce** [comment]
@rooneywp , speaking for USDS, it's very helpful for us to track where our candidates are getting referred from, and we would like to continue to know who came to our application by way of 18F's website.

When an actual 18F human refers someone to USDS, the candidate should write the name of the referrer in the referral code field.
cc: @JenTress

**Comment by pixelwake** [comment]
Captured in PR #148

**Comment by fureigh** [comment]
Thanks for the quick reply, @kimballce! Very helpful.
