### ISSUE TITLE
Rewording referral section 

### ISSUE THREAD

**Issue by hestherchang** [18F/joining-18f#113]
Currently reads "If someone referred you to us, please include their name."

However, candidates also have referral codes we gave them (they aren't people names). Can we pls include something like the message below under "Where did you learn about 18F?"?

"if someone referred you to us, please include their name. If you have a referral code, please include that in the box below." 

@jamiealbrecht  any ideas to make it less wordy?

**Comment by jamiealbrecht** [comment]
How about: Please mention names of the 18F Team Member that referred you or a code if applicable.

**Comment by hestherchang** [comment]
Perfecto!

**Comment by fureigh** [comment]
But people are sometimes referred by non-18Fers, no? If Todd Park referred an applicant, I wouldn't want them to refrain from mentioning that just because he's not an 18F team member.

How about:

> Please include a name or referral code if applicable.

**Comment by fureigh** [comment]
On second thought:

> If applicable, please include a name or referral code.

...so it doesn't read as "you must _always_ include a name, but include a referral code only if applicable."

**Comment by fureigh** [comment]
@hestherchang I went ahead and submitted a pull request (#117) but feel free to make further edits.
