### ISSUE TITLE
Edit: About the "why:"

### ISSUE THREAD

**Issue by hestherchang** [18F/joining-18f#114]
On the application, (I think) it should be...

About the "why": 

not... About the "why:" (switch colon & closing ")

**Comment by fureigh** [comment]
[You're](http://blog.apastyle.org/apastyle/2011/08/punctuating-around-quotation-marks.html) [right](http://www.scribd.com/doc/2664713/Associated-Press-AP-Style-Guide-the-basics#scribd)!

Happy to take a few minutes on Friday to share how to make and propose these changes yourself, if you'd like. @jamiealbrecht can attest it's not that scary. :)

**Comment by hestherchang** [comment]
Yeah - would def like to learn! I thought all issues had to be submitted through here but yes, definitely would like to make edits as needed. I'll find some time for us on Friday - thanks :)
