### ISSUE TITLE
Join 18F Application: Eligibility

### ISSUE THREAD

**Issue by pixelwake** [18F/joining-18f#115]
This issue doesn't required immediate action.

@fureigh What do you think about making the Eligiblity quesiton required? I know that there is only one response possible, but if we make it required then the applicant will either be unable to submit the application or they will be forced to lie if they do not, in fact, meet eligibility requirements.

There are a few applicants that didn't submit a response but based on other information, I'm guessing it was an oversight and not that they aren't actually eligible.

**Comment by pixelwake** [comment]
@fureigh actually just realized that for some reason no one is checking the box. I was previously looking at old responses. In the previous form, most people checked the box so I'm not sure what has triggered the behavior change

**Comment by fureigh** [comment]
@rooneywp I'll check the code to see whether something changed there (such as the value that's being logged).

I've been inclined to not require that field because it runs the risk of people submitting false positives, accidentally or otherwise, which is different from someone actively clicking the checkbox. I'm willing to require it as a stopgap measure, though.

**Comment by fureigh** [comment]
@rooneywp One was logged today, so I believe it's a UX issue. How about I move the eligibility question to the top of the form? My thinking on that is:
1. People will be most attentive to the first question on the form, and
2. If someone's _not_ eligible, we don't want to waste their time with any other questions.

**Comment by pixelwake** [comment]
Let's give it a shot and see if response rate goes up. I agree that a false
positive is more costly and we want to avoid.

What about changing the format of the question to have two choices, a yes
and a no choice? Then requiring? I know it's been a single response format
from the beginning but I'm not sure if there is an actual requirement there.

**Comment by fureigh** [comment]
@rooneywp Good call; the current checkbox approach is drawn from the example of the Presidential Innovation Fellows' application.

I just moved the eligibility question. If that doesn't fix it, reopen this issue and I'll change the question to be required and have yes/no answers.
