### ISSUE TITLE
Join 18F Application: Automated email sent after form completion

### ISSUE THREAD

**Issue by pixelwake** [18F/joining-18f#118]
A confirmation email is sent to candidates that have successfully submitted an application.

Problem: Applicants are unsure if their application was successfully submitted and reaching out to talent team to confirm if their application has been received.

Note: I just wanted to capture this issue somewhere. It may not be something that we can or will want to do with this interim solution but didn't want to lose the feedback.

**Comment by fureigh** [comment]
They should currently see a confirmation message on-screen, but it's understandable that they'd be more certain if they also received an email. Thanks for capturing this feedback.

**Comment by fureigh** [comment]
Flagging as related to #153.

**Comment by pixelwake** [comment]
@fureigh We may be able to close this issue as I think it was also addressed by #156 Thoughts?

**Comment by fureigh** [comment]
@rooneywp #156 should make it clearer to applicants that they've submitted the application, but applicants may still want a confirmation email... a spot of user research could address this question.

**Comment by fureigh** [comment]
@rooneywp Safe to assume Lever handles this?

**Comment by fureigh** [comment]
Confirming; tested on Lever and it works. Closing.
