### ISSUE TITLE
Clarify what to expect if your application isn't "qualified" at the GS level you select

### ISSUE THREAD

**Issue by fureigh** [18F/joining-18f#132]
Specifically, that reclassification to a different level isn't a matter of negotiation but instead requires reapplying.

**Comment by fureigh** [comment]
Entails delay but no detriment to evaluation of application.

**Comment by fureigh** [comment]
This information is now in paragraph three of [Government pay grades explained](https://pages.18f.gov/joining-18f/pay-grades/). There's no guarantee that the applicant will have noticed and reviewed that page, though.

@rooneywp, can you add help text to the Lever applications' question "Please select the position (grade level) that you are applying to" and include a link to the [Government pay grades explained](https://pages.18f.gov/joining-18f/pay-grades/) page?

**Comment by pixelwake** [comment]
@fureigh Unfortunately, formatting options are really limited in the job postings. You can't add help text to questions within the application so it would have to exist in the title of the question itself. Also, it doesn't allow hyperlinking so it would need the full address. Example below:
![image](https://cloud.githubusercontent.com/assets/13383307/12209287/c92545d2-b606-11e5-9936-410a9849b2a9.png)

Currently, it is linked at the bottom of the job description itself, but that is separate from the application and currently we are hosting the description on Join 18F and not using the page hosted in Lever. Example:

![image](https://cloud.githubusercontent.com/assets/13383307/12209349/25e5e2b8-b607-11e5-97e5-0bcac2921cc8.png)

**Comment by coreycaitlin** [comment]
This is most relevant for our old process (selecting GS level from a drop-down). The newer process, which should provide clearer distinction between levels and qualifications, will hopefully make this less relevant. Also, Talent team members can advise individuals of their options later in the process as-needed.

**Comment by coreycaitlin** [comment]
Also! this language is now in this section: https://18f.gsa.gov/join/#government-pay-grades
