### ISSUE TITLE
Update Interview Process

### ISSUE THREAD

**Issue by elainekamlley** [18F/joining-18f#14]
Criteria: 
- [ ] Image of 18F org structure 
- [ ] what teams (consulting, delivery) and roles are available for consideration
- [ ] Provide timeline breakdown from application submission to security clearance

**Comment by afeld** [comment]
> Image of 18F org structure

/cc https://github.com/18F/hub/issues/31

> what teams (consulting, delivery) and roles are available for consideration

Could you elaborate? Seems like https://pages.18f.gov/joining-18f/who-we-are-hiring/ shows the options.

**Comment by elainekamlley** [comment]
@afeld Having options listed there are really great and much more that we have had before but they are still a little confusing. Consulting job profiles have a different format and feel to them than the rest so along with the picture of the org, adding some text around how to navigate the roles could provide clarity. @awfrancisco @emileighoutlaw are also working on this with me. If they want to add any comments.

**Comment by pixelwake** [comment]
Closing this issue, addressed performance profile issues and captured remaining here #143
