### ISSUE TITLE
Join 18F Application - Re-add the preference levels to Vet question

### ISSUE THREAD

**Issue by pixelwake** [18F/joining-18f#146]
Based on requirements from HR, we need to have each of the levels available for the applicant to selection from.

Here are the categories:

0-point Sole Survivorship Preference (SSP).
5-point preference based on active duty in the U.S. Armed Forces (TP).
10-point preference based on a compensable service connected disability of at least 10% but less than 30% (CP).
10-point preference based on a compensable service connected disability of 30% or more (CPS).
10-point preference for non-compensable disability or Purple Heart (XP).
10-point preference based on widow/widower or mother of a deceased veteran, or spouse or mother of a disabled veteran (XP)

**Comment by pixelwake** [comment]
@fureigh Just added this issue

**Comment by fureigh** [comment]
@rooneywp Right-o. These are the same as the ones we had before, right?

**Comment by pixelwake** [comment]
@fureigh We should use whatever we had on the site before. I can't remember if what I listed are the same as before but what we had before takes precedent over what I listed.
