### ISSUE TITLE
Add language to application response that indicates to close window

### ISSUE THREAD

**Issue by pixelwake** [18F/joining-18f#152]
When the application is submitted and the green box appears stating it has been submitted, the user is unclear of where to navigate next. Feedback has been that it "stalls out". This may also have resulted in people refreshing the page and double submitting.

**Comment by fureigh** [comment]
There's discussion in #153 about having a confirmation page instead of a modal window. If we go that direction, I believe it'll eclipse this ticket.

**Comment by fureigh** [comment]
@rooneywp, now that #156 is merged, this may no longer be necessary. Take a look at the current application and let me know what you think.

**Comment by pixelwake** [comment]
@fureigh Agreed. #156 addressed this issue. Closing.
