### ISSUE TITLE
Update position descriptions' permalinks to be in 'roles-and-teams', not 'who-we-are-hiring'

### ISSUE THREAD

**Issue by fureigh** [18F/joining-18f#155]
Now that role descriptions are on a 'Roles and Teams' page (#130), let's update the position descriptions to be nested under `roles-and-teams`, not under `who-we-are-hiring`.

**Technical notes:**
- Update the permalink. For an example, see #140.
- Be sure to preserve redirects in cases where the position page is extant (i.e., unless the position in question is a brand-new page). Use `jekyll-redirect-from` per #82.

**Comment by afeld** [comment]
Are there longer job descriptions that should be linked to from https://pages.18f.gov/joining-18f/roles-and-teams/? Sorry that I'm coming into this without context.

**Comment by fureigh** [comment]
@afeld Sorry about the delayed reply! There were, and then there weren't, and now yes, they've been reinstated.

**Comment by fureigh** [comment]
@afeld To clarify: there's currently a discrepancy between the active positions, whose permalinks follow the pattern `roles-and-teams/positions/POSITION-NAME/`, and the inactive positions ([example](https://github.com/18F/joining-18f/blob/18f-pages/_positions/agile-coach.md)), whose permalinks follow the pattern `who-we-are-hiring/positions/POSITION-NAME/`.

**Comment by fureigh** [comment]
Closing this as irrelevant now that the position descriptions are hosted on Lever.
