### ISSUE TITLE
Clarify what kind of résumé is needed

### ISSUE THREAD

**Issue by fureigh** [18F/joining-18f#159]
We're not using a federal résumé in the technical sense, but we are requesting something longer than most workplaces would want.

Are the guide and example résumés listed on the [How to apply](https://pages.18f.gov/joining-18f/how-to-apply/) page still relevant? If not, let's create amended versions. They could conceivably be useful to other digital service teams in the future.

**Comment by fureigh** [comment]
Bumping and sending over to @rooneywp. Are the guide and example résumés listed on the [How to apply](https://pages.18f.gov/joining-18f/how-to-apply/) page still relevant?

**Comment by hollyallen** [comment]
I'm also interested in this. The example resumes can be intimidating, as noted by @coreycaitlin . Can we find better examples, or create a new example from whole cloth?

**Comment by coreycaitlin** [comment]
I believe this was resolved by including better guidance, which has been migrated here: https://18f.gsa.gov/join/#government-style-resumes
