### ISSUE TITLE
Dynamic display of the point in time of the current application sprint

### ISSUE THREAD

**Issue by pixelwake** [18F/joining-18f#161]
**User story:** As an applicant I want to know the point in time of the current sprint that I am applying so that I can have a better idea of the expected timeline

**Comment by fureigh** [comment]
I'd love to hear more about this. Can you give an example? Is the sprint cycle predictable or does it change (whether because of holidays or agency needs or otherwise)? Happy to hop on a call if it's simpler to explain in realtime.

**Comment by coreycaitlin** [comment]
This seems unrealistic right now, given the constraints on hiring and the variability of timelines.
