### ISSUE TITLE
Join Page and/or Application: Add emphasis/clarity to how the application will be used

### ISSUE THREAD

**Issue by pixelwake** [18F/joining-18f#162]
Issue: Applicants may not understand the importance of the application package and because of that, may not be investing as much time into their submission.

Potential solution: Add language to the Join Page and Application (or link to information) that states that this is the information that will be used to determine whether or not they will be selected for interview.

**Comment by fureigh** [comment]
Is there reason to believe this is still an issue?

**Comment by pixelwake** [comment]
I think that we can close this issue. With the move to Lever and a more conventional application, applicants do not have worry about formatting, etc. They can upload resumes, which avoids the need to reproduce or copy/paste.
