### ISSUE TITLE
Multiple applications submitted in rapid succession

### ISSUE THREAD

**Issue by fureigh** [18F/joining-18f#165]
Seven identical applications were submitted milliseconds apart around 8:46 a.m. today. #156 was meant to preclude this but the problem persists.

**Desired behavior:**
Only one application is recorded per submission.

**Actual behavior:**
Sometimes multiple application records are created in rapid succession, apparently triggered by the same submission.

**Steps to reproduce:**
Not yet clear.

**Comment by fureigh** [comment]
@xtine, are you game to look into this? I ask because of the possible connection to #156.

**Comment by fureigh** [comment]
@xtine Bump. Any thoughts on this?

**Comment by xtine** [comment]
I'm still trying to figure this out. Since I've pushed up a fix for this (disable form submit upon successful click), there have been fewer multiple apps submitted but still happens from time to time.

**Comment by fureigh** [comment]
Hmm, thanks for the update. The switch to Lever (#189) should render this issue moot.

**Comment by fureigh** [comment]
Thanks again for your work on this, @xtine.

I'm closing this issue due to the switch to Lever. @rooneywp, if you hear of this issue recurring, please reopen.
