### ISSUE TITLE
Ensure Relative URLs

### ISSUE THREAD

**Issue by SeanKilleen** [18F/joining-18f#185]
As noted in #157, URLs within the markdown aren't always relative, which can be cumbersome when building/viewing pages locally. 

I'm happy to take care of this.

**Comment by SeanKilleen** [comment]
FYI, I'll create a WIP PR and push many small changes. I'll squash at the end if desired.

**Comment by fureigh** [comment]
@SeanKilleen No need to squash; a WIP PR with many small changes sounds perfect. Thanks for your work on this!

**Comment by SeanKilleen** [comment]
@fureigh sorry to bug on this -- it's a little more complex than I initially thought.

## The Problem
The issue is that in some cases (e.g. locally), a relative URL (e.g. `/page/mypage`) will be from the hosted jekyll site (e.g. `http://localhost:4000/page/mypage`). However, when hosted, the link would actually need to be `pages.18f.gov/joining-18f/page/mypage`, and that extra sub-site will break the relative URLs.

I think I'll handle it using [the Jekyll recommended steps found here](http://jekyllrb.com/docs/github-pages/#project-page-url-structure). This seems to be the standard way of doing it, and should allow us to publish this easily with minimal changes to the build process.
