### ISSUE TITLE
Joining 18F Application - Make role selection required and a drop down

### ISSUE THREAD

**Issue by pixelwake** [18F/joining-18f#187]
Restrict people to only applying for the specific roles that are listed on our roles and teams site.
- [x] #183 merged to update roles and teams  
- [x] Update "what role" question on application

**Proposed Change**

**Question**
Current: "What role or team at 18F do you believe you're the best fit for and why?"
Proposed: "Please select the role that you would like to apply to"

**Format:** Text Box to Drop down

**Required:** Yes

**Help text:**
"For more information about the available roles, please refer to [this page](https://pages.18f.gov/joining-18f/who-we-are-hiring/). If you don't see a role that is a good fit for you, please check back soon as our needs change frequently."

**Drop Down values:**
Director of Outreach
Design and Product Strategist
Front End Designer
Product Lead
Software Developer
Site Reliability Engineer
Visual Designer

**Comment by pixelwake** [comment]
@fureigh this is an issue that we would like to address quickly. Let me know if you have any questions or need additional info. Also feel free to make whatever copy edits you see fit.

**Comment by fureigh** [comment]
@rooneywp Thanks for the heads-up. I have to head out for the night but will address this first thing in the morning.

**Comment by pixelwake** [comment]
Updated the drop down values

**Comment by fureigh** [comment]
@rooneywp Where did you update the dropdown values?

**Comment by pixelwake** [comment]
@fureigh in the main issue comment

**Comment by fureigh** [comment]
@rooneywp Right-o, thanks for clarifying. Making those changes in the form now.

One issue in the meantime: not all roles listed above are currently represented on the roles page in #183. Want to add/restore them in #183?

**Comment by pixelwake** [comment]
@fureigh Yep, #183 was updated to include all those roles now

**Comment by fureigh** [comment]
@rooneywp As someone who's been reviewing applications, I'll be sorry to lose the "and why?" element of the application, which has been helpful in contextualizing people's self-evaluations and interests. Is the goal to make it easier to categorize and sort responses? If so, what if we added a "why" textbox after the dropdown?

**Comment by fureigh** [comment]
@rooneywp Thanks for updating #183!

**Comment by pixelwake** [comment]
@fureigh The primary intent is to limit incoming applications to only those that are for roles we are actively looking to fill (though this will make assigning SMEs much easier as well).

I like the idea of still including an essay, it could say something like "Tell us why you think you are a good fit for this role". Copy can be changed however, but I agree that the spirit of the essay is really useful.

**Comment by fureigh** [comment]
In progress in #188.

**Comment by fureigh** [comment]
@rooneywp Thoughts on whether applicants should be restricted to just one role?

**Comment by pixelwake** [comment]
@fureigh Yes, let's restrict them to one role per application. We won't restrict them to submitting only one application though. This is will also be the case when we switch to Lever but with that application it will be a better experience for them.

**Comment by fureigh** [comment]
@rooneywp Making applicants resubmit every single piece of their information when only two fields (which role and why) seems rough. Closed this issue for now because the main points have been addressed, but will Lever reduce the amount of duplicate information they have to enter?

**Comment by pixelwake** [comment]
@fureigh Yep, Lever will allow the applicant to apply to multiple roles using the same information and only providing additional that is unique to that posting (though in our case they will likely be the same).

**Comment by fureigh** [comment]
@rooneywp Glad to hear it. Thanks!
