### ISSUE TITLE
Application to Join 18F Link URL Validation Fails if Trailing Whitespace Present

### ISSUE THREAD

**Issue by Grantimus9** [18F/joining-18f#203]
Problem: 
Under "Where can we find you online" on the [application](https://pages.18f.gov/joining-18f/pages/apply.html), the URL validations don't strip trailing whitespace prior to validating. Result is a failing validation for what _appears_ to be a valid URL, most troublesome when copy-pasting a URL into the field.

**Comment by fureigh** [comment]
Thanks for filing this bug report, @Grantimus9!

This appears to be fixed now that we've transitioned to a different application system in #189. Closing for now, but if the issue persists, please reopen.
