### ISSUE TITLE
Lever deleting field contents when part of application fails validation

### ISSUE THREAD

**Issue by fureigh** [18F/joining-18f#217]
**Current behavior:**
When validation fails, most if not all fields from "Application Questions" onward are cleared.

**Desired behavior:**
When validation fails, all fields' contents are preserved. This is so they can be simply edited or left alone instead of having to be reentered.

**Steps to reproduce:**
1. Go to an application in Lever (say, the [Software Developer](https://jobs.lever.co/18f/40d0f4ee-be99-47be-be03-29b2095e51f6/apply) one).
2. Enter content into all fields _except_ a required field (say, the Veterans' Preference field).
3. Click the 'Submit Application' button.
4. Observe as the application form loses the contents of several fields.

Discovered while testing #203.

**Comment by fureigh** [comment]
@rooneywp, does Lever offer configuration options that would prevent this?

**Comment by pixelwake** [comment]
@fureigh There isn't a configuration option that we have access to. I submitted the bug to our Lever account manager. Will post response here.

**Comment by fureigh** [comment]
@rooneywp Okay, thanks!

**Comment by pixelwake** [comment]
Update: Contacted last week by Lever helpdesk, they are still looking into the issue.

**Comment by fureigh** [comment]
Thanks for the update.

**Comment by fureigh** [comment]
@rooneywp Any news on this one?

**Comment by pixelwake** [comment]
@fureigh No updates. I followed up with the support team just now, will update if I get a response.

**Comment by coreycaitlin** [comment]
We're no longer using Lever.
