### ISSUE TITLE
App down

### ISSUE THREAD

**Issue by JenTress** [18F/joining-18f#220]
Looks like the app is down on this page: https://pages.18f.gov/joining-18f/how-to-apply/
Routes to the roles page.

**Comment by fureigh** [comment]
Hmm, even with a shift-reload I'm unable to reproduce this bug. Here's what I see in Chrome:

![screen shot 2016-01-04 at 5 00 19 pm](https://cloud.githubusercontent.com/assets/1244599/12104878/77981f8c-b304-11e5-81e8-abe8287bcf56.png)

Can you try again and send a screenshot if the error persists?

**Comment by JenTress** [comment]
Worked!

**Comment by fureigh** [comment]
👌
