### ISSUE TITLE
Short URL for 18F Application

### ISSUE THREAD

**Issue by hestherchang** [18F/joining-18f#221]
Create a short, easy to remember URL for this page: https://pages.18f.gov/joining-18f/index.html

Idea for short link: join.18F.gov or 18F.gov/join 

Some things to think about: 
1. Is https://pages.18f.gov/joining-18f/index.html the page we want to directly refer candidates to? 
1. Is "join" the word we want to use in the short URL? Is there something more appropriate like "apply"? 
2. Can this short URL be useful? 

@rooneywp @cbrydges @jamiealbrecht @JenTress @JennMoran @ScottPia @shawnique : your thoughts?

**Comment by JennMoran** [comment]
@hestherchang I like this idea - I have a hard time remembering this webpage myself and think shortening it to something like join18.gov will be much easier

**Comment by jamiealbrecht** [comment]
:+1:

**Comment by hestherchang** [comment]
@afeld, Is there something I need to do to get this short link created? It'd be nice to have it done by Thurs 1/14 - going recruiting on Friday 1/15 and would like to use a short link

**Comment by fureigh** [comment]
Good news: join.18f.gov already exists! We're good to go. :)
