### ISSUE TITLE
Product team is only hiring for PMs in areas we have offices

### ISSUE THREAD

**Issue by hestherchang** [18F/joining-18f#227]
State that new Product Leads are only accepted in areas we have offices - Chicago, NYC, DC, SF

**Comment by fureigh** [comment]
@hestherchang, I'm assigning this to you to reflect that you're working on it. :+1:

**Comment by fureigh** [comment]
@hestherchang, I made a few other copy changes in #228 — if they look good to you, please update the Lever text accordingly.

**Comment by fureigh** [comment]
Closing because this appears to have been incorporated into [the Lever listing](https://jobs.lever.co/18f/6cafb4ed-45c1-4a0f-b004-7da14dd04eb1). If there's more to do here, @hestherchang, please reopen the issue.
