### ISSUE TITLE
Post Technical Account Manager - Cloud.gov position on Lever

### ISSUE THREAD

**Issue by hestherchang** [18F/joining-18f#230]

**Comment by hestherchang** [comment]
Waiting for few more pieces of information from Noah Kunin before I can post this.

**Comment by fureigh** [comment]
@hestherchang Closing this issue because I see [what appears to be a listing](https://jobs.lever.co/18f/4eb35e9c-03e2-405f-8ba3-58e31be06092). If there's more to do here, please reopen.
