### ISSUE TITLE
Reinstate links to more information for GS level and Veterans Preference questions

### ISSUE THREAD

**Issue by fureigh** [18F/joining-18f#235]
Before the switch to Lever, the application included links to more information for applicants trying to decide how to answer the GS level and Veterans Preference questions. I no longer see them, at least not when accessing the application from my phone's browser (ex: https://jobs.lever.co/18f/40d0f4ee-be99-47be-be03-29b2095e51f6/apply).

Please reinstate them! :) If you'd like me to pull up the past version for ease of copying and pasting, just reassign this issue to me.

**Comment by pixelwake** [comment]
@fureigh  The links you are referencing are currently being house on the[ job description part of the application.](https://jobs.lever.co/18f/6cafb4ed-45c1-4a0f-b004-7da14dd04eb1)

![image](https://cloud.githubusercontent.com/assets/13383307/12653848/3735eb18-c5a6-11e5-878f-caa9601b3aa3.png)

Formatting options within the application questions themselves is very limited, there is not way to include links or any formatting. The only way to include the link information is in the following example:

![image](https://cloud.githubusercontent.com/assets/13383307/12654087/3fd862c2-c5a7-11e5-8cf3-7797b4f8f2c7.png)

It will not actually be a hyperlink, just the text.

Maybe there is a way to address this on the join page itself? A way to call enough attention to the information so the user see's it before proceeding. Or maybe some kind of gate, additional click, that stops the user at this information?

**Comment by fureigh** [comment]
Thanks for the screenshot and the helpful explanation, @rooneywp. I'm glad the list of resources exists as a fallback. I'd rather include the link information per your example ("Format Test Form"). It's inconvenient (and problematic from an accessibility standpoint) that it's not clickable, but that's better than omitting it from that form entirely. It's important to show the information at the point at which it's relevant. Does that work for you?

Alternately, the field help text on the applications _could_ say something like "For help answering this question, see the links at the bottom of the previous page." But that's awfully clunky as a user experience, especially after someone's already started filling out the form.

Perhaps we could also change the header above that list of links to make clearer that we're not just providing those resources to be friendly; you'll need these to answer questions on the next page.

If you haven't already done so, it'd be good to give Lever feedback about this.

**Comment by pixelwake** [comment]
@fureigh Here are the proposed updates to the posting and application. These changes were made to the template, once reviewed I'll update the existing postings.

[Job Posting](https://jobs.lever.co/18f/ae5ec9a1-73e5-4bb1-bd4c-ea90b5ea905e)

![capture1](https://cloud.githubusercontent.com/assets/13383307/13607428/f2ba19ae-e504-11e5-8246-2674cdb83652.PNG)

[Application Questions](https://jobs.lever.co/18f/ae5ec9a1-73e5-4bb1-bd4c-ea90b5ea905e/apply)

![capture2](https://cloud.githubusercontent.com/assets/13383307/13607472/24b21902-e505-11e5-9069-fefd011ccaff.PNG)

**Comment by fureigh** [comment]
Thanks, @rooneywp! A few suggestions:

**Job Posting:**
How about this?

> Please review the following links; they'll help you answer application questions on the next page. You may want to open them in separate tabs for ease of reference.

**Application Questions:**
Let's change the question mark to a period at the end of "Please select the position (grade level) that you are applying to." (Could also change to "to which you're applying," if we want to be sticklers about grammar.)

All else looks good to me.

**Comment by pixelwake** [comment]
This issue can be closed. #258 now captures the changes.
