### ISSUE TITLE
Add rss feed

### ISSUE THREAD

**Issue by melodykramer** [18F/joining-18f#237]
Hello!

It might be helpful to add an RSS feed to the join site so that people can see new jobs that are posted. I've found this helpful in the past - and it's easy for people to then set up an IFTTT rule or something similar to have new positions emailed to them.

Mel

**Comment by fureigh** [comment]
Great idea!

**Comment by fureigh** [comment]
@rooneywp, checking before building something: do you know whether this is functionality Lever provides? I'd imagine so, but I don't see anything in their documentation and https://jobs.lever.co/18f/ and https://api.lever.co/v0/postings/18f don't cut it.

**Comment by pixelwake** [comment]
@fureigh I didn't see anything either. They just launched their data api https://hire.lever.co/developer/documentation which might be something that we can use to support this.

**Comment by fureigh** [comment]
Thanks, @rooneywp. Possible approaches include https://hire.lever.co/developer/documentation#postings or working with one of the URLs above, then.

**Comment by quepol** [comment]
Since we're hiring in sprints now, I think this functionality is very important. I talk to people all the time and basically tell them, we've got discrete positions on the website, but we're constantly evaluating our needs and our bench, so check back often.

Mostly just +++'ing this issue. :)

**Comment by coreycaitlin** [comment]
I think the primary call to action for updates is now the newsletter, which should suffice for the current pace of hiring.
