### ISSUE TITLE
Change "Roles and teams" page title to "Open positions"

### ISSUE THREAD

**Issue by quepol** [18F/joining-18f#238]
Since this page no longer describes the different teams, but is rather the listing of open positions, as a user I would like to more easily find that in the navigation.

**Comment by fureigh** [comment]
Good call. Thanks!

Though now that you mention it, general information about roles and teams really would be useful (and used to exist)... I can look for it in the git history.

**Comment by fureigh** [comment]
@rooneywp Is there a technical/policy-based reason we need to use `role` instead of `position`? If not, let's default to `position`.

**Comment by quepol** [comment]
Awesome change in the link on the top two pages in the nav. What do folks also think about changing the actual nav item from `Roles and teams` to `Open positions`?

The link is at the bottom of the first two pages, which is great, but I'd also love for it to be more intuitive to find what positions we're hiring for **in the navigation itself**. (Sorry if that wasn't clear from my first comment. Probably got garbled trying to make it sound like a user story. :)

**Comment by fureigh** [comment]
@quepol Thanks for revisiting this. That's a great suggestion; I'll implement it.

I may have muddied the waters a bit by saying I'd like to _also_ include a rundown of what roles and teams exist at 18F. I'll make a separate ticket for that for clarity's sake.

**Comment by fureigh** [comment]
Ready for review in #249.
