### ISSUE TITLE
Add functional tests

### ISSUE THREAD

**Issue by fureigh** [18F/joining-18f#247]
**User story:**
As a site owner, I want to be confident that the site's links work correctly and that all necessary content is present.

**Technical notes:**
Let's get some Selenium tests in here.

**Comment by fureigh** [comment]
No immediate capacity to work on this, but I'm noting it so it doesn't get lost.

**Comment by coreycaitlin** [comment]
This should also be resolved by the migration to the 18F site (https://18f.gsa.gov/join/), which has a number of tests present.
