### ISSUE TITLE
Restore information about roles and teams

### ISSUE THREAD

**Issue by fureigh** [18F/joining-18f#248]
...as distinct from open positions. See #238 for earlier conversation.

**Comment by fureigh** [comment]
**User story:**
As a prospective applicant, I want to know what kind of organization I'm considering going into and who I'd be working with.

**Technical notes:**
For possible content, refer to the git log of `/pages/roles-and-teams.md`, present in d027de102d421bea07bde6814f8a4ffb419ce14d and earlier.

**Comment by coreycaitlin** [comment]
This is a larger project, which the Talent team is tackling outside of this repo.
