### ISSUE TITLE
who are we hiring? update.

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/joining-18f#25]
A few things: 
1. Remove business analyst, digital performance analyst, and delivery manager from the page completely. 
2. Put interaction designer, etc under design
3. Please take off anything related to content. No current openings.

cc @awfrancisco @elainekamlley 

Apologies if this is the complete wrong way to do this. :) But thank you in advance.

**Comment by emileighoutlaw** [comment]
I'm on this!

**Comment by emileighoutlaw** [comment]
Actually, scratch that "I'm on this." The page is pulling positions from a list, so I'm not sure how to update?

**Comment by awfrancisco** [comment]
I can walk you through it. Will DM.
