### ISSUE TITLE
Certain Links Not Working

### ISSUE THREAD

**Issue by dijonkitchen** [18F/joining-18f#250]
The following links are not working. The markdown files are in the pages directory so maybe it's a Jekyll issue. 

https://pages.18f.gov/joining-18f/how-to-apply/

https://pages.18f.gov/joining-18f/benefits/

https://pages.18f.gov/joining-18f/benefits/

https://pages.18f.gov/joining-18f/leave-policies/

https://pages.18f.gov/joining-18f/conferences-training-travel/

**Comment by fureigh** [comment]
@dijonkitchen Thanks for this! I'm currently able to load all of those pages — can you confirm whether this is still an issue?

**Comment by dijonkitchen** [comment]
Working now! Thanks!

**Comment by fureigh** [comment]
Thanks for confirming!
