### ISSUE TITLE
Redirect link that goes to open positions.

### ISSUE THREAD

**Issue by melodykramer** [18F/joining-18f#251]
@rooneywp @fureigh 

Please put a redirect on this former page: https://pages.18f.gov/joining-18f/roles-and-teams/ to this page: https://pages.18f.gov/joining-18f/open-positions/

The former link is on a lot of sites and those links no longer work (and it is easier to redirect the old page than to change all of the older links)

**Comment by pixelwake** [comment]
Changes reverted in #252, original PR is #249

**Comment by fureigh** [comment]
@melodykramer Thanks for catching this. #249 should've accounted for that — I'll look into why the redirect didn't work.

**Comment by fureigh** [comment]
(And @rooneywp, thanks for getting a hotfix out.)

**Comment by fureigh** [comment]
@rooneywp Ready for review in https://github.com/18F/joining-18f/pull/253.

**Comment by fureigh** [comment]
Fixed. (https://pages.18f.gov/joining-18f/roles-and-teams/ now successfully redirects to https://pages.18f.gov/joining-18f/open-positions/.)
