### ISSUE TITLE
Pay Grades: Increase visibility for compensation calculations

### ISSUE THREAD

**Issue by pixelwake** [18F/joining-18f#254]
**Issue:** Compensation ranges and locality pay may not be clearly illustrated to potential applicants.

Per @vzvenyach "hey all… after seeing this tweet https://twitter.com/dberkholz/status/707416531290947584 i checked out how we describe our pay on https://pages.18f.gov/joining-18f/pay-grades/ and i wonder whether it’s misleading for folks who live in large cities. near the top of the page, we list the pay range for each of the grades, but we don’t highlight the locality adjustment. and when we ​_do_​ mention the locality adjustment we only provide the amount for the ​_bottom_​ of grade 14, not the range, or for grade 15"

"That pay tho. You've gotta really want to go gov. https://twitter.com/mkramer/status/706944596463325184"

"i know we link to the salary calculator, but it’s not very visible, and if you’re casually skimming for compensation range, it’s definitely not obvious what the low and the high might look like for an individual considering applying. i ​_think_​ we could fix this by expanding the table with locality adjustments to include additional grades and include ranges"

**Comment by pixelwake** [comment]
I don't believe that this is a high urgency issue but it's worth investigating. We can always make improvements to our site.

**Comment by fureigh** [comment]
Oh, good call. It'd be simple enough to add corresponding ranges (not just bases) for GS-13, GS-14 and GS-15... reasonable? The writing lab folks may have other ideas for how to improve this.

**Comment by fureigh** [comment]
@rooneywp, is this something you'd be willing to take a crack at?

**Comment by hollyallen** [comment]
Have we considered greatly simplifying the "Compensation in the GS pay system" section? Speak to the overall cap of $160,300, then link to OPM. One paragraph.

**Comment by hollyallen** [comment]
I created the above PR as an example of simplified language. @fureigh suggested user testing this page with potential applicants which I think is :+1:

**Comment by pixelwake** [comment]
PR looks fine and user testing would be great.

**Comment by fureigh** [comment]
Closed that PR — thanks, @hollyallen! Will wrangle potential applicants with whom to test. :)

**Comment by hollyallen** [comment]
I had a chance to do ad hoc user research with a applicant who was in the office for potluck. She did not see the guidance for gov't resumes at all, and said that the differences between the GS levels were really unclear. She also said that it was unclear what the difference between the "Why 18F?" and "cover letter" sections of the application were. 

She suggested a checklist for applicants, with govt style resume at the top. I like this idea.

**Comment by rdpiazza** [comment]
So I'm not sure the best way to explain this to people applying, but one thing that I don't think is clear is that your grade level determines some of your career advancement opportunities once you're here, since it's more challenging (and sometimes not possible) for GS-13s or GS-14s to be facilitators or to compete for Director positions. If someone is picking based entirely on salary or being conservative, they may block themselves out of opportunities down the line.

**Comment by coreycaitlin** [comment]
Resolved by a number of content additions and subtractions.
