### ISSUE TITLE
Update 'Open positions' to pull only 18F projects

### ISSUE THREAD

**Issue by fureigh** [18F/joining-18f#255]
As https://github.com/18F/joining-epa spins up and we add any EPA (i.e., other agencies') listings to Lever, we'll need to make sure they don't show up on this site (`join.18f.gov`).

**Technical note:**
Update `leverpostings.js`.

Corresponds to https://github.com/18F/joining-epa/issues/13.

**Comment by coreycaitlin** [comment]
This is no longer relevant, since we've stopped using Lever.
