### ISSUE TITLE
Add 'Why did you join 18F' to main page of Joining 18F repo

### ISSUE THREAD

**Issue by melodykramer** [18F/joining-18f#257]
I think [this blog post](https://18f.gsa.gov/2016/03/21/we-asked-100-of-our-coworkers-why-did-you-join-18f/) which asks everyone why they joined 18F would be really helpful to feature on our recruiting page.

**Comment by melodykramer** [comment]
Same with the [path post](https://staging.18f.gov/2016/03/22/what-was-your-path-to-18f/)

**Comment by fureigh** [comment]
Super useful posts! Perhaps they could go on https://pages.18f.gov/joining-18f/who-we-are-hiring/? I'll draft something in a pull request and send it your way.

**Comment by fureigh** [comment]
Ready for review in #259.
