### ISSUE TITLE
Lever applicants may never see or know about join.18f.gov

### ISSUE THREAD

**Issue by fureigh** [18F/joining-18f#258]
Now that we’re using Lever, a lot of people are sharing the position listings directly rather than sending people to join.18f.gov. That's cool, but I realized during a conversation with @melodykramer that the Lever posts (ex: https://jobs.lever.co/18f/65b74f21-2b8d-4e38-ba23-b90551d4a82b) don’t include any links to join.18f.gov. Which means many applicants are likely missing all of the context we’ve carefully provided over at join.18f.gov.

I’d say the Lever posts should all include a directive link (“Please review the materials at join.18f.gov for important context”, say). Other ideas? @rooneywp, do you need anything more to make this feasible?

**Comment by pixelwake** [comment]
@fureigh @melodykramer I can add this pretty easily. Are we good with the copy "Please review the materials at join.18f.gov for important context"?

Maybe add something like "that will help ensure you successfully apply". Something to create some urgency on the user to follow the link?

**Comment by rdpiazza** [comment]
When people have the direct link to Lever, they can also apply to positions that are not currently open.  Is there a way to also direct people to join.18f.gov check make sure the position is currently taking applications?  Or does it just make sense to reject them? We've had people apply when the position isn't open.

**Comment by fureigh** [comment]
@rooneywp @melodykramer How about "For important context, please see join.18f.gov." Frontloading the urgency without adding more words.

Or a friendlier take: "For important context, you'll want to read join.18f.gov."

**Comment by melodykramer** [comment]
How about "Before applying, go to https://join.18f.gov to read important information about preparing your application."

**Comment by fureigh** [comment]
@rdpiazza Is there no way to mark positions 'closed' in Lever? I hope we can resolve that issue on the Lever end if at all possible rather than shifting the burden to the applicant.

**Comment by fureigh** [comment]
@melodykramer That phrasing sounds good to me. (Can cut the https from the link text for the sake of conciseness.)

**Comment by melodykramer** [comment]
Sounds good!

**Comment by pixelwake** [comment]
@rdpiazza Nothing we can to systematically because we need to keep the job "open" so that we can still transact against it. We don't publish the jobs that aren't truly open but if they have the direct link already they will be able to apply.

The text editing is pretty limited on the job posting and even more so on the application. But we we could find a place to house that text.

**Comment by rdpiazza** [comment]
It's not a huge deal!  This is a pretty infrequent issue.

**Comment by pixelwake** [comment]
@fureigh @melodykramer 

This is what we currently have on the job posting:
![image](https://cloud.githubusercontent.com/assets/13383307/13996982/347b96c6-f0ed-11e5-8283-9ac3d8af3935.png)

Do we want to replace it with this:
![image](https://cloud.githubusercontent.com/assets/13383307/13997084/9f0801be-f0ed-11e5-853c-7c91dde322c5.png)

**Comment by melodykramer** [comment]
How's this:

Before applying, go to join.18f.gov to read important information related to government pay grades, the application process, and how our interviews work.

**Comment by melodykramer** [comment]
That gets at everything in both, and really spells out that they should visit that site.

**Comment by fureigh** [comment]
Hmm — the thinking behind having those specific links called out is that the next page (i.e., the application itself) requires the applicant to answer questions with reference to those links. (Which GS level they're selecting, for instance.)

I'm fine with replacing it with the second version (adding a period at the end of the sentence, please) if we also add something like "We recommend keeping join.18f.gov open for ease of reference while you answer application questions."

**Comment by pixelwake** [comment]
Now for the application itself, our options are very limited but if we wanted to include this direction, we could house it in a question and place it before the other questions.

![image](https://cloud.githubusercontent.com/assets/13383307/13997313/ae10101a-f0ee-11e5-98eb-5bac889465cf.png)

**Comment by fureigh** [comment]
@rdpiazza To that issue (which we probably should've broken out into its own GitHub issue, but oh well): how about whomever administers the postings simply adds a note to any closed postings so they're self-documenting? Something like "We're not currently accepting applications for this position. For a list of open positions, please see join.18f.gov."?

**Comment by melodykramer** [comment]
I really like that idea @rooneywp and @fureigh (the splitting out the specifics as well as that question box!)

**Comment by pixelwake** [comment]
I have updated and tested the new links and copy. You can see the copy live here: https://jobs.lever.co/18f/65b74f21-2b8d-4e38-ba23-b90551d4a82b

**Comment by pixelwake** [comment]
I also went ahead and added the question to the application. It's not required, it's only intended as a reminder to the applicant to reference the site.

You can see the live version here: https://jobs.lever.co/18f/65b74f21-2b8d-4e38-ba23-b90551d4a82b/apply

@fureigh @melodykramer ^

**Comment by pixelwake** [comment]
@fureigh @melodykramer When I wrote the update above, I didn't include your names and added them as an update. Not sure if it notifies you when done that way, so thought I'd just write a new one :) No rush on this, just wanted to make sure you were aware.

**Comment by fureigh** [comment]
Looks great, @rooneywp! Thanks also for changing that reminder checkbox to be friendlier. :)

> join.18.gov has useful information about government pay grades, the application process and interviewing at 18F

@melodykramer, wanna close this one?
