### ISSUE TITLE
Expose high-level timeline of application/hiring process

### ISSUE THREAD

**Issue by afeld** [18F/joining-18f#261]
I just had a candidate ask about the timeline for the the application, interview, and hiring process, and realized that we don't really lay that out anywhere. Maybe it could go at the top of the [interview process](https://pages.18f.gov/joining-18f/interview-process/) page, which links down to the other sections? Example:

> - **Day 0:** Submit application
> - **Week 5:** Hear back about whether you will be interviewed or not
> - **Week X:** First interviews will be scheduled
> - **Week Y:** Tentative offer will be made
> - **Week Z:** Official offer will be made
> 
> Note that this timeline is aspirational, and isn't always consistent from one candidate to another.

/cc @hestherchang

**Comment by hestherchang** [comment]
I really like this. Great suggestion, Aidan. 

How about...

Day 0: Submit application
Week 5: Hear back about whether you will be interviewed or not
Week 7: Preliminary screen will be scheduled
Week 9: Panel interview will be scheduled 
Week 11: Tentative offer will be made
Week 13: Official offer will be made

Note that this timeline is aspirational and candidates may experience a variation of this timeline. 

@JennMoran @jamiealbrecht @shawnique @cbrydges - Does this sound about right? Are you comfortable with this information being shared to candidates on our join page? Setting expectations with our candidates is always something we can always improve.

**Comment by fureigh** [comment]
Great suggestion. Let's be sure to define "tentative offer;" we can pull from existing language on the [how to apply](https://github.com/18F/joining-18f/blob/f182077d60122ce356e3c33e72a75c7132877bd8/pages/how-to-apply.md) page.

**Comment by JennMoran** [comment]
I think this is a great idea - but first would like to see how Sprint 6
plays out to make sure this timeline is accurate.

On Mon, Mar 28, 2016 at 6:35 PM, Fureigh notifications@github.com wrote:

> Great suggestion. Let's be sure to define "tentative offer;" we can pull
> from existing language on the how to apply
> https://github.com/18F/joining-18f/blob/f182077d60122ce356e3c33e72a75c7132877bd8/pages/how-to-apply.md
> page.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/18F/joining-18f/issues/261#issuecomment-202606334

## 

Jennifer Moran
Recruitment Coordinator / Executive Administrator - Talent Team
https://18F.gsa.gov | @18F

**Comment by pixelwake** [comment]
I agree with @JennMoran. I'm hesitant to post timelines like this given how the previous sprints have been running. Even if we caveat the timeline, my feeling is that it would cause more anxiety if the candidate had milestones like that and they were missed, as opposed to a total for the process.

**Comment by afeld** [comment]
What if we started out with the timelines being even looser? e.g. "several weeks", "2-4 months", etc.

**Comment by coreycaitlin** [comment]
see #161
