### ISSUE TITLE
Should applications mention New York as a "preferred work location" option?

### ISSUE THREAD

**Issue by fureigh** [18F/joining-18f#265]
Currently they do. New York has a critical mass of 18Fers but no office space, which may be the case in a few other locations too.

Continuation of a conversation in #262.

**Comment by pixelwake** [comment]
@fureigh Oh, interesting thought. It might be giving applicants the impression that we actually have an office/work space there. My gut says that it would be rare instances when someone thought there was an office and applied but found they would be remote in that city and then it made the situation unacceptable. But doesn't mean we still couldn't find a way to make it clearer.

**Comment by coreycaitlin** [comment]
We have to list locations in individual job postings (if relevant), but we no longer list "preferred work locations" on the general Join 18F page.
