### ISSUE TITLE
Folks are submitting apply when they are not eligible

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/joining-18f#267]
We get a number of applications from folks that indicate that they are not eligible for the job. Perhaps there is a way to put that question to the top? Or remind people of it earlier on? Or make the language more human? It's confusing & wordy as it stands.

**Comment by fureigh** [comment]
@jamiealbrecht Can you give an example or two of what's coming through (i.e., the indications that they're not eligible)?

**Comment by jamiealbrecht** [comment]
Great question! We're not really capturing what is making them ineligible. My guess it's the citizenship / green card thing in most cases, but we're not going beyond the sending them a note that says that because that they indicated that they are not eligible we are taking that at face value. We do say if it's an error to let us know, but I've never received a response indicating it was indeed an error.

All I am seeing is an estimated 2-3 people per sprint in design that indicate that they don't meet the eligibility requirements, which I feel bad that they didn't figure that out before going through the trouble of uploading their info.

Does that make sense?

**Comment by fureigh** [comment]
Oh, I see — so they're marking `I do not meet the above eligibility requirements` in response to this question?

> Any individual who is not currently a GSA employee or contractor and who is a U.S. citizen, a non-citizen national of the U.S. or holds a valid green card is eligible to apply.

If that's the case, let's move that question to the top of every application, above résumé.

Let's also consider changing the 'no' answer to something that more clearly communicates how to proceed. Safe to assume people who on these grounds are ineligible for 18F are also ineligible for USDS? I'm wondering whether there's somewhere else we could encourage them to turn.

**Comment by jamiealbrecht** [comment]
Exactly. Agree we should move it to the top. 

Hrm. I am not sure what USDS permits. It would be good to suggest an alternative.

**Comment by pixelwake** [comment]
@fureigh @jamiealbrecht 

This portion of the application is fixed and we have no control over:

![image](https://cloud.githubusercontent.com/assets/13383307/14743429/59cb9194-0856-11e6-8d5e-26224c013d39.png)

The furthest that the eligibility question can be moved is here:

![image](https://cloud.githubusercontent.com/assets/13383307/14743398/44175d74-0856-11e6-82c4-14a811f7c0a0.png)

**Comment by coreycaitlin** [comment]
This is much more clearly noted at the top of the new [Join 18F page](https://18f.gsa.gov/join/#how-to-apply), and is also much more prominent individual job postings.
