### ISSUE TITLE
Change question mark to period in grade level question

### ISSUE THREAD

**Issue by fureigh** [18F/joining-18f#268]
**Current:**
Please select the position (grade level) that you are applying to?

**Desired:**
Please select the position (grade level) that you are applying to.

**Steps to replicate:**
1. Go to https://jobs.lever.co/18f/85ac9796-537e-46ea-aa62-a75ec363bdcc/apply, for instance.
2. Scroll down.
3. Read the prompt text of the relevant field.

**Technical notes:**
The Lever admin interface is where to make this change.

**Comment by pixelwake** [comment]
@fureigh Updated the application question as requested. Changes are live on all forms. Issue is ready to be closed.

Sample:
![image](https://cloud.githubusercontent.com/assets/13383307/14711505/63ff05f6-078e-11e6-92be-8dfb95691f18.png)

**Comment by coreycaitlin** [comment]
No longer using Lever.
