### ISSUE TITLE
"Gory" language on parental leave

### ISSUE THREAD

**Issue by awfrancisco** [18F/joining-18f#269]
Emailed comment:

> I am so impressed by the work done by 18f. You're all doing so many cool things!
> I would like to kindly suggest a modification to the 18f leave policies page, where it says "all the gory details" under Parental Leave - perhaps there is another adjective that can replace "gory"? 

https://pages.18f.gov/joining-18f/leave-policies/

**Comment by fureigh** [comment]
:) Thanks, @awfrancisco! How about we just cut 'gory' for now.
