### ISSUE TITLE
explain innovation specialist

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/joining-18f#27]
I think it might be worth talking about that everyone here is an "innovation specialist" in the eyes of GSA. People start to get offers and then are confused as to what that means.

Also, please tell me if this is the wrong way to suggest edits. :)

**Comment by fureigh** [comment]
@jamiealbrecht: Let's pair on this! I'll put some time on your calendar to sit down and get you set up to submit pull requests. :rocket:

**Comment by fureigh** [comment]
Accidental assignment, sorry @alanswx! :)

**Comment by fureigh** [comment]
Closing this because it's handled in #100.
