### ISSUE TITLE
Update Join page language for application intake closure

### ISSUE THREAD

**Issue by pixelwake** [18F/joining-18f#271]
Since we will be closing applications on 5/1, we need to make potential candidates aware of this upcoming change.

**Part 1 - Target 4/28**
The PR #272  contains the language that we would like to post on Join 18F. The initial proposal is to include this content on the Open Positions page but it could be included other places if it would be more effective.

**Part 2 - Target 5/9**
Once the applications are closed, we would like to update the content to include a link that would allow people to sign up with their name and email address for a talent newsletter. We will use the newsletter to update them with new openings, etc.

@fureigh Thinking that we could repurpose the content for the original google form application to accomplish this.

cc @jamiealbrecht

**Comment by fureigh** [comment]
@rooneywp: Does a talent newsletter currently exist? If not, where's the work to create that happening?

**Comment by jamiealbrecht** [comment]
it doesn't exist. @amandaschonfeld and i will be working on what that might look like. however, the vision for this for the moment is for us to be able to capture folks who are interested in joining and be able to update them when positions go back up. Amanda and I will be handling outreach to folks during the intake pause either by phone or email.

**Comment by fureigh** [comment]
@jamiealbrecht Cool. Separately from the question of what the newsletter content will look like, someone will need to figure out how to capture folks' info (i.e., where it should be stored). What does 18F use for regular newsletter mailings currently?

**Comment by fureigh** [comment]
(Relevant: #57)

**Comment by fureigh** [comment]
ccing @awfrancisco, who may know the answer to that question.

**Comment by jamiealbrecht** [comment]
was just about to hit up andre! i imagine we can do what we do for the 18f site.

**Comment by awfrancisco** [comment]
We use MailChimp, and other teams have been setting up project-specific mailing lists using the 18F MailChimp account. Micro-purchase has one and I think the Digital Acquisitions Pilot does too. I believe #infrastructure should be able to get someone access, then embedding or linking to the form is pretty easy. Then it's easy to separate out your list from everyone else inside MailChimp.

**Comment by fureigh** [comment]
Thanks, @awfrancisco! @jamiealbrecht / @rooneywp, who on the Talent side will run (and set up) that list?

**Comment by fureigh** [comment]
Bump: @jamiealbrecht / @rooneywp, can one of you set up this list today so I can integrate it? Slack me if you have questions. I'm on East Coast time today.

**Comment by fureigh** [comment]
cc @hestherchang

**Comment by hestherchang** [comment]
@rooneywp  jamie isn't working on mailchimp. are you @rooneywp ? if not, i can take it on.

**Comment by pixelwake** [comment]
@hestherchang Nope, all you.

**Comment by fureigh** [comment]
Part two is ready for review in #274.

**Comment by fureigh** [comment]
Closing!

![high-five-group-saved-by-the-bell](https://cloud.githubusercontent.com/assets/1244599/14966547/0ddfcc04-1081-11e6-8f6c-0f63bc9d22e5.gif)
