### ISSUE TITLE
Bug in email sign up form

### ISSUE THREAD

**Issue by hestherchang** [18F/joining-18f#280]
Interested candidates cannot subscribe to our email list. Multiple have received this error: 
Too many subscribe attempts for this email address. Please try again in about 5 minutes. (#8343)

[MailChimp FAQ](https://us9.admin.mailchimp.com/lists/members/add?id=676805) says... 

Error message: Too many subscribe attempts for this email address. Please try again in about 5 minutes.
What it indicates: The email address cannot be subscribed to the list because too many attempts have been made to add it within a short timeframe. It can also indicate browser-related issues.

How to fix it: Wait several minutes to see if you are able to successfully sign up with the email address or try a different browser. If your browser has an auto-fill setting, try turning it off—it can fill a hidden field that we include in the code to prevent spam signups.
We recommend keeping the hidden field in your signup form to prevent bots from signing up spam email addresses to your list. But it can be removed from your embed form code by deleting the following from the code on your site:

<div style="position: absolute; left: -5000px;"><input type="text" name="xxxxx" value=""></div>

(there is supposed to be a string of code here but don't know how to get it to appear! it disappears when i hit 'update comment'. you can see the string of code if you click the MailChimp FAQ link above) 

Could we get the above code removed from our page please? Fingers crossed this fixes the bug. I know it only happens with some candidates because I signed up with my personal to see if I'd get the same error and I did not/was able to successfully sign up. 

Thank you!

**Comment by fureigh** [comment]
@hestherchang Thanks for the bug report.

I can't see the code in that Mailchimp FAQ because it requires a login, which I don't have. Can you try to paste that code again? Enclosing it in tick marks — ` ` — should do the trick.

**Comment by fureigh** [comment]
ccing @msecret

**Comment by hestherchang** [comment]
`<div style="position: absolute; left: -5000px;"><input type="text" name="xxxxx" value=""></div>`

woohoo! thanks for the tip

**Comment by fureigh** [comment]
@hestherchang Thanks for that code. Have candidates been able to sign up after waiting five minutes?

**Comment by fureigh** [comment]
I ask because it's true that the form will be defenseless against spambots otherwise. I've seen mailing lists with that problem before and it's not pretty. :)

**Comment by hestherchang** [comment]
According to one candidate, nope. "I want to subscribe to receive 18F open
role updates.  However I get an error saying there are too many attempts
from my email even after trying again in 30 minutes"

Ah :( If it's between being defenseless against spambots and having
candidates sign up without any errors... I choose the latter.

Although I am wondering if removing that line of code is the only way to
solve the issue..

_H. Esther Chang_
18F Talent Team
U.S. General Services Administration
1800 F St NW, Washington, DC

**Comment by fureigh** [comment]
Definitely agreed about those priorities. I'll take a quick look.

**Comment by msecret** [comment]
Is the code here:
https://github.com/18F/joining-18f/edit/18f-pages/pages/open-positions.md
lines 11-44?

**Comment by fureigh** [comment]
@msecret Just the hidden field (line 40).

The idea behind this approach to fighting spambots is that humans don't see the field, so they don't fill it out, but spambots still see a field, so they fill it out, and _then they've blown their cover and we know they're bots._ :)

Ready for testing at https://pages-staging.18f.gov/joining-18f/open-positions/ and review in #281. @msecret, are you game to review it?

**Comment by hestherchang** [comment]
(does this mean this is fixed?)

_H. Esther Chang_
18F Talent Team
U.S. General Services Administration
1800 F St NW, Washington, DC

**Comment by fureigh** [comment]
@hestherchang: Yep! Closed = fixed. If the issue recurs, please reopen this issue.

**Comment by fureigh** [comment]
(If the problem recurs, that is.)

**Comment by hestherchang** [comment]
thanks so much to you both! 🙌

**Comment by veitch123** [comment]
Still happening for me.

**Comment by fureigh** [comment]
@veitch123 Sorry to hear that — thanks for reporting! Were you able to get your application in? (cc @hestherchang)

**Comment by fureigh** [comment]
@veitch123 Can you provide steps to reproduce this bug? The signup no longer exists on join.18f.gov; it's at https://18f.gsa.gov/#newsletter instead, where I was just able to sign up with a test account.

**Comment by coreycaitlin** [comment]
I believe this has been resolved. Please open a new issue in the [18F site repo](https://github.com/18F/18f.gsa.gov/issues) if this reoccurs for the newsletter form.
