### ISSUE TITLE
Add some guidance on experience level

### ISSUE THREAD

**Issue by afeld** [18F/joining-18f#282]
From @gboone [in Slack](https://18f.slack.com/archives/dev/p1463761881001260):

> I just talked to some students at [bootcamp] and they had some questions about what we're looking for in terms of experience for dev hires

Not sure if this should be included on a position-by-position basis (when they open up again), or if it makes sense to include something on [who are hiring](https://pages.18f.gov/joining-18f/who-we-are-hiring/).

**Comment by fureigh** [comment]
I'd suggest on a position-by-position basis, as we hire for lots of non-dev roles too. @hestherchang, could some of this be drawn from the criteria guide you started? If not, who would know how best to proceed?

**Comment by coreycaitlin** [comment]
See #129 — now handling on position-by-position basis.
