### ISSUE TITLE
Application confirmation email from lever includes no 18F contact information

### ISSUE THREAD

**Issue by hollyallen** [18F/joining-18f#283]
Currently when an applicant submits an application, they are not given any way to contact us for follow up. Say their application is taking weeks to progress to the next stage, they have nobody to reach out to. Consider including a contact email address for applicants as part of the application process.

See issue #143 for context of how the current application confirmation email wording was devised.

**Comment by fureigh** [comment]
Thanks for reporting this, @hollyallen! @rooneywp, would you be up for adding something like this to the end of the email confirmation?

> If you have any questions in the meantime, you can reach us at join18f@gsa.gov.

**Comment by coreycaitlin** [comment]
No longer using Lever.
