### ISSUE TITLE
Add confirmation of successful email list subscription

### ISSUE THREAD

**Issue by neilmartis** [18F/joining-18f#285]
When submitting First Name,Last and clicking on Subscribe no notification or email is received about subscribing to the email list.I tried to subscribe but haven't received any notification of subscription.

**Comment by fureigh** [comment]
Thanks for reporting this, @neilmartis!

@rooneywp, can you check whether there's a setting to enable this? (ccing @hestherchang)

**Comment by pixelwake** [comment]
@hestherchang is admin of the list, she'll be able to verify.

**Comment by hestherchang** [comment]
Hi, @neilmartis . The only thing that comes to mind is that the confirmation email could be in your spam. The function for subscribers to received a confirmation welcome email is still enabled and hasn't been changed. If you can provide us with your email, I'd be happy to add you to the list so you can get updates. Feel free to send it to join18F@gsa.gov to my attention if you'd rather not share your email here. 

Esther

**Comment by ghost** [comment]
@hestherchang I will email you on my email address.Thank you

**Comment by ghost** [comment]
@hestherchang I have checked my email box as I do receive emails about the micropurchase but not this one

**Comment by fureigh** [comment]
@neilmartis Has this been resolved? Other people have reported receiving sign-up confirmation emails, though sometimes they go to spam.

**Comment by ghost** [comment]
@fureigh Sorry for the late reply Yes I have received the email but I heard that 18F is not going to send any emailers .
"We will no longer be using this mailing list to send updates regarding hiring. If you are interested, you can sign-up to receive the 18F Newsletter which is sent out every two weeks and has information about 18F in general but will also includes updates specific to our hiring needs."

**Comment by fureigh** [comment]
@neilmartis Okay — I'll close this issue, as the initial issue you reported has been resolved.

The change you referenced was made just a few days ago in https://github.com/18F/joining-18f/pull/296. If you'd like to offer feedback about the current user experience, I invite you to do so there. Thanks in advance!
