### ISSUE TITLE
Unpaid leave - Only FMLA?

### ISSUE THREAD

**Issue by pburkholder** [18F/joining-18f#294]
In `pages/leave-policies.md` it seems the only options for unpaid leave are:
- after 12 months of employment AND
- within the first 12 months of child's birth/adoption.

Are there other options for unpaid leave? Or are sick leave and annual leave the only options there are?

Thanks, Peter

**Comment by fureigh** [comment]
Thanks, Peter! I believe the Family and Medical Leave Act is a bit more extensive than that:

> In addition to the types of leave detailed above, the Family and Medical Leave Act (FMLA) allows most federal employees to take up to 12 weeks of **unpaid** leave per 12-month period for: the birth or care of a child, an adoption or placement of child for foster care, the care of a spouse/son/daughter/parent with a serious health condition, a serious health condition of an employee, or a qualifying exigency from spouse, child or parent of an employee on covered active duty in the Armed Forces. An employee is entitled to taking FMLA when they have been an employee of the federal government for **at least 12 months.**
> 
> Former members of the military and/or a military service academy can receive credit for their time. They’ll need to fill out form [FERS 3108](https://www.opm.gov/forms/pdf_fill/sf3108.pdf). An employee who has transferred from another agency can use their time to count toward the 12-month restriction.
> 
> The Department of Labor has a [detailed guide to FMLA](http://www.dol.gov/whd/fmla/), including this [FMLA FAQ](http://www.dol.gov/whd/fmla/fmla-faqs.htm).

I don't see the part about unpaid leave only being possible after 12 months of employment... Can you provide a line number or a quote, @pburkholder?

(And @cbrydges, can you weigh in on the above? Thanks!

**Comment by cbrydges** [comment]
Employees can request/take unpaid leave (a week or 2 but not 12 weeks worth) at any time - they do not have to have been employed for 12 months.  

Thanks - Cristina

**Comment by fureigh** [comment]
@pburkholder, I don't see the part about unpaid leave only being possible after 12 months of employment... can you provide a line number or a quote? Or clarify `leave-policies.md` if unclear?

**Comment by pburkholder** [comment]
@fureigh I didn't see unpaid leave addressed at all except wrt FMLA, so I've opened #315.  Does that suffice?
