### ISSUE TITLE
Not clear whether to include resume and cover letter

### ISSUE THREAD

**Issue by fureigh** [18F/joining-18f#314]
Following up on #304, based on a question from a potential applicant:

The positions (such as [this one](https://pages.18f.gov/joining-18f/raas/hud/software-developer/)) say `If you would like to apply to this opportunity, please email join18f@gsa.gov and reference this position.`

Should applicants include a resume and cover letter in that email? If so, let's say so. If not, let's explicitly say they don't need to.

**Comment by fureigh** [comment]
@rooneywp, what's your take?

**Comment by rachellegupta** [comment]
I think the candidate should include their resume, I agree it's not clear cc/ @rooneywp 

I'm ok without the cover letter. 📄

**Comment by coreycaitlin** [comment]
We're no longer collecting applications via the email address, and the form clarifies this issue.
