### ISSUE TITLE
Adding 18F Talent Team built skeleton resume to join page

### ISSUE THREAD

**Issue by hestherchang** [18F/joining-18f#328]
**Current wording on join page for resumes** 
When you apply, you’ll need to include a current, government-style resume. Government-style resumes are very different from private-sector resumes. [Here is a guide](http://gogovernment.org/how_to_apply/write_your_federal_resume/create_your_resume.php) and an [example resume](http://www.fda.gov/downloads/AboutFDA/WorkingatFDA/UCM279014.pdf). Please overexplain, include dates of each engagement, and include everything and the kitchen sink.

**Proposed wording**
When you apply, you will need to include a government-style resume. A government-style resume is very different from a private-sector resume, a major difference being the depth of detail required throughout the entire resume.

There are many guides on how to build a government-style resume on the web and no two resources are alike. This guide (_our skeleton resume pdf will be linked here_) shows how to format the resume, shares the key pieces to include, and is most relevant to applying to 18F. 

Additional resources from other organizations are below if you'd like to use it as a reference: 
- [GoGovernment's Create your federal resume guide](http://gogovernment.org/how_to_apply/write_your_federal_resume/create_your_resume.php)
- [Food and Drug Administration (FDA)'s Federal Resume Template](http://www.fda.gov/downloads/AboutFDA/WorkingatFDA/UCM279014.pdf) 

@amandaschonfeld @rachellegupta thoughts on the proposed wording?

**Comment by hestherchang** [comment]
ping @rachellegupta  @amandaschonfeld @cbrydges (now that you are back!)

**Comment by amandaschonfeld** [comment]
Propose that we edit this sentence to read this way instead: A government-style resume is very different from a private-sector resume; one major difference being the depth of detail required throughout the entire resume.

Also propose we should make a slight change to this sentence too: Additional resources from other organizations are below if you'd like to use them as a reference:

**Comment by rachellegupta** [comment]
I think it's good, only thing I thought maybe specify that it's ok for your government resume to be several pages long? But really I'm fine keeping the language as you proposed.

**Comment by hestherchang** [comment]
Thanks for the feedback @rachellegupta  @amandaschonfeld 

**Final wording for join page**
When you apply, you will need to submit a government-style resume. A government-style resume is very different from a private-sector resume; one major difference is the depth of detail required throughout the entire resume. Because of the level of detail required, It is completely acceptable for your government-style resume to be several pages long. 

There are many guides on how to build a government-style resume on the web and no two resources are alike. [This guide](https://github.com/18F/joining-18f/files/551292/SkeletonGenericResumeFINAL.pdf) is most relevant to apply to 18F. It also shows how to format a government-styled resume and shares the key pieces to include.

Additional resources from other organizations are below if you'd like to use them as a reference:
[GoGovernment's Create your federal resume guide](http://gogovernment.org/how_to_apply/write_your_federal_resume/create_your_resume.php)
[Food and Drug Administration (FDA)'s Federal Resume Template](http://www.fda.gov/downloads/AboutFDA/WorkingatFDA/UCM279014.pdf)

**Comment by cbrydges** [comment]
looks great.  thanks all.

**Comment by fureigh** [comment]
🎉 This is great! Continuing the conversation in #329.
