### ISSUE TITLE
What is the difference between... who-we-are-hiring vs agile-labor-categories

### ISSUE THREAD

**Issue by jackiekazil** [18F/joining-18f#33]
https://pages.18f.gov/joining-18f/who-we-are-hiring/
http://18f.github.io/agile-labor-categories/

Should we kill the second one? 
/cc @gboone

**Comment by afeld** [comment]
This question has been raised before, but can't find the conversation. @cscairns?

**Comment by cscairns** [comment]
@afeld @jackiekazil: don't kill the agile bpa labor categories...they are for contracts...18F is using these labor categories in the interim until we fully transition to performance profiles

**Comment by jackiekazil** [comment]
:+1: Since this is documented, I am going to close this issue.

**Comment by gboone** [comment]
FWIW: If that github.io page is being distributed to members of the public it should probably be migrated to pages.18f.gov. cc: @NoahKunin

**Comment by afeld** [comment]
Already is:

https://pages.18f.gov/agile-labor-categories/

/cc https://github.com/18F/agile-labor-categories/issues/5
