### ISSUE TITLE
Preparing to post roles again 

### ISSUE THREAD

**Issue by hestherchang** [18F/joining-18f#334]
Job application to be posted: https://docs.google.com/a/gsa.gov/forms/d/1xiHCBMvagoEWpW_VCmcjECDfcS0HbZDS7guen-hYhAk/edit

Working on getting the google form ready to be posted

**Comment by fureigh** [comment]
Thanks, @hestherchang!

**Comment by fureigh** [comment]
Quick question: previously, we held off on asking for legal name (if different from preferred name) until later in the process. Is there a reason that it's needed at this point?

**Comment by fureigh** [comment]
Technical note: simplest is to reinstate and update the application form (and accompanying elements) we had circa 9beed21eca4fc905519d7d3157d4736d387f20a1.

**Comment by hestherchang** [comment]
need to create a new page for the new job posting to live

**Comment by hestherchang** [comment]
fyi: job posting went to HR for approval today

**Comment by fureigh** [comment]
Work-in-progress pull request at #335.
