### ISSUE TITLE
Staging is down

### ISSUE THREAD

**Issue by fureigh** [18F/joining-18f#339]
**Steps to reproduce:**
1. Go to https://pages-staging.18f.gov.
2. Observe the following error:

> 404 Not Found: Requested route ('pages-staging.18f.gov') does not exist.

**Technical notes:**
This may be a migration issue.

**Comment by coreycaitlin** [comment]
I believe this is overtaken by the pages/federalist changes AND the migration to the 18F site. Reopen if not.
