### ISSUE TITLE
Update info on 'Government pay grades explained'

### ISSUE THREAD

**Issue by fureigh** [18F/joining-18f#340]
Now that we're no longer hiring against the Innovation Specialist position description, the information on https://pages.18f.gov/joining-18f/pay-grades/ needs to be updated.

Per @hestherchang's note in #335. Relates to #334.

**Comment by hestherchang** [comment]
https://github.com/18F/joining-18f/blob/18f-pages/pages/pay-grades.md

I thought I made a pull request but looks like my edits were just committed?

**Comment by fureigh** [comment]
@hestherchang Yep. 😬 I'll take a look

**Comment by fureigh** [comment]
Closed in b7f1155 and 9ea42eb :)
