### ISSUE TITLE
Review competencies listed on Interview Process page

### ISSUE THREAD

**Issue by rdpiazza** [18F/joining-18f#350]
The Interview Process page (https://pages.18f.gov/joining-18f/interview-process/) lists competencies that candidates will be evaluated against.  These may not be correct now that we are no longer hiring against the Innovation Specialist PD.  Recommend reviewing for accuracy.

**Comment by coreycaitlin** [comment]
We removed these in the migration to the new [Join 18F page](https://18f.gsa.gov/join/), and competencies will be included in individual postings going forward.
