### ISSUE TITLE
Move to Federalist

### ISSUE THREAD

**Issue by fureigh** [18F/joining-18f#353]
Per https://docs.google.com/document/d/1ZQDKPZbmUkoVtSrY61GUuBbDukauDo9brCQPvS5lObg/edit

**Comment by fureigh** [comment]
Added the GitHub repository.

Remaining steps:
- [ ] Configure CDN
- [ ] Configure DNS

**Comment by fureigh** [comment]
Next step is to hang tight while the site gets cleared.

**Comment by wslack** [comment]
@fureigh this is a moot issue now, correct? If so, should the site be deleted from Federalist? https://federalist-proxy.app.cloud.gov/site/18f/joining-18f/ still serves.

**Comment by wslack** [comment]
cc @gemfarmer

**Comment by fureigh** [comment]
Good catch! Yep, I believe so. (cc @coreycaitlin)

**Comment by fureigh** [comment]
Closing this issue — if I'm mistaken, please reopen.

**Comment by wslack** [comment]
@fureigh can y'all delete https://federalist-proxy.app.cloud.gov/site/18f/joining-18f/ from Federalist so we aren't serving unneeded content?

**Comment by fureigh** [comment]
@wslack Will do!
