### ISSUE TITLE
Need to change email address on Join page

### ISSUE THREAD

**Issue by JennMoran** [18F/joining-18f#355]
The Join18F email has been changed to JoinTTS.  Can you please rewrite the following line:
If you have any questions, please contact our Talent Team at join18f@gsa.gov

to say:
If you have any questions, please contact our Talent Team 

and have Talent Team be linked to the jointts@gsa.gov email?

This needs to be done ASAP as people trying to email join18F are no longer able to since email was just changed cc @awfrancisco @elainekamlley 

Thank you!

**Comment by elainekamlley** [comment]
No problem, will make the change shortly.
