### ISSUE TITLE
Benefits section to be more inclusive of specific health provider information

### ISSUE THREAD

**Issue by elainekamlley** [18F/joining-18f#5]
As part of the #wg-diversity meeting, we discussed being more transparent on what government health providers cover. Some examples include trans related health care, coverage for pregnancy, HIV, diabetes, etc. I'm not sure if we have to be specific about everything but we should have some basic language to speak to these without promoting a plan over another. First step is to research. Who can help us find these answers?

**Comment by rdpiazza** [comment]
I might be able to help.  I spent a lot of time combing through the health plan specs before joining, trying to figure out the differences, so I feel comfortable poking around them.  What's the goal?  Something more general saying that there are plans available that cover X, Y, and Z, or more of a comparison cheatsheet that lists all of the plans and shows which ones cover certain benefits and which ones don't?

**Comment by esgoodman** [comment]
I'd say the vaguer format would be better.  Less effort to create and
maintain over time, while still letting people know they have options  (or
not).

**Comment by fureigh** [comment]
Bump. The [benefits page](https://pages.18f.gov/joining-18f/benefits/) currently provides links to health insurance plans, though applicants are left to dig through and determine for themselves which plans cover (and exclude) what. Should I mark this `wontfix`?

**Comment by fureigh** [comment]
Marking this as `wontfix` and closing. Please feel free to reopen.
