### ISSUE TITLE
Eligibility for the PSLF and other student debt relief benefits

### ISSUE THREAD

**Issue by gboone** [18F/joining-18f#6]
The Public Service Loan Forgiveness program forgives all remaining debt on federal loans after 120 payments while employed full time in public service. It's unclear, based on [the FAQ](https://studentaid.ed.gov/sa/repay-loans/forgiveness-cancellation/public-service#hundred-twenty-payments), whether the time must be with the _same_ employer, or whether it can be spread across multiple jobs. If there's any loan forgiveness benefits to joining 18F, we should highlight them.

Similarly, there is the [Student Loan Repayment Program](http://www.opm.gov/policy-data-oversight/pay-leave/student-loan-repayment/) that potential applicants (and current employees) might be curious about if there's any way 18F can participate in that.

**Comment by pixelwake** [comment]
-bump-

Don't want to lose this issue. This could be an excellent recruiting/retention tool for 18F.

**Comment by gboone** [comment]
Totally agree. I got an answer form my loan servicer about the "same employer" question: It does not need to be the same employer, nor do the 120 payments need to be continuous. Based on that it would seem like if you came from a qualifying organization, the 48 payments made while you're with 18F would count toward your 120.

The Student Loan Repayment Program would also be a good retention tool.

**Comment by fureigh** [comment]
:+1: Thanks for raising the issue, @gboone, and for bumping it, @rooneywp. Definitely doesn't need to be same employer or continuous.

@gboone, would you be game to draft copy or a pull request for this?

**Comment by gboone** [comment]
Will do; will post the draft here when it's going.

From the Student Loan Repayment Program page:

> Any employee (as defined in 5 U.S.C. 2105) is eligible, except those occupying a position excepted from the competitive civil service because of their confidential, policy-determining, policy-making, or policy-advocating nature (e.g., Schedule C appointees).

I assume that is not us, though we are excepted from the competitive civil service, right?

Also:

> An employee receiving this benefit must sign a service agreement to remain in the service of the paying agency for a period of at least 3 years.

Since our contracts are NTE 2 years with a renewal option. Does that mean we're not eligible or only eligible after we reup for years 3-4?

**Comment by fureigh** [comment]
Hmm. Who might know the answer to these questions (or who would know)? @cbrydges? @JenTress?

**Comment by cbrydges** [comment]
This would be a question for our benefits specialist - Marty.  I will send her an email and let you know what she says.  BTW - sorry for the delayed response - not used to GitHub (learning) and am getting a lot of messages from it right now :)

**Comment by fureigh** [comment]
Thanks, @cbrydges! Happy to help with GitHub sometime if you like; @jamiealbrecht can provide references. :) In the meantime, I'll assign this issue to you so it's clear that you're the person currently moving it forward.

**Comment by gboone** [comment]
Just heard from Marty about the Student Loan Repayment Program: The short answer is no. Most 18F employees do not qualify for the Student Loan Repayment Program because we are not permanent hires and do not have a 3 year commitment, even though we could end up serving > 3 years before leaving. Anybody that's not in the 2 + 2 situation (Smart IT, Peace Corps hires, etc.) might qualify. [Here's GSA's implementation plan for the SLRP.](http://www.gsa.gov/portal/directive/d0/content/537130)

**Comment by fureigh** [comment]
Thank you for researching that, @gboone.

Everyone's still eligible for the [Public Service Loan Forgiveness Program](https://studentaid.ed.gov/sa/repay-loans/forgiveness-cancellation/public-service#hundred-twenty-payments), though, right?

**Comment by gboone** [comment]
As far as I know, your time served here should count toward the PSLF if you apply for it, yes. The maximum benefit would be 48 qualifying payments. 

The catch there is PSLF is based on number of payments, not time served. So 10 years working isn't _necessarily_ enough if you have a deferment or forbearance for any reason. My understanding is that even if you make a payment when you aren't obligated to, it is not a _qualifying_ payment and doesn't count for PSLF. There are also certain repayment plans that don't count. You have to be on a standard 120 payment or income based plan in order to qualify — Standard counts, Extended doesn't.

Some (all?) loan servicers put payers in an administrative forbearance whenever they switch or adjust repayment plans. In my experience those can last up to 3 months. It might be worth advising new hires to attempt to check their repayment situation before they start so they can get the maximum benefit.

**Comment by fureigh** [comment]
> It might be worth advising new hires to attempt to check their repayment situation before they start so they can get the maximum benefit.

@gboone, would you be game to draft something to that effect (or a pull request for all of the above)?

**Comment by gboone** [comment]
I'll see what I can do :)

**Comment by coreycaitlin** [comment]
We removed this from the Join 18F page when we edited it down significantly for inclusion in the 18F site, but it was added to the handbook with this PR: https://github.com/18F/handbook/pull/280
