### ISSUE TITLE
link to this repository from the site

### ISSUE THREAD

**Issue by afeld** [18F/joining-18f#60]

**Comment by fureigh** [comment]
@afeld I was about to add a "Feedback about this site?" page to the side nav, but upon closer examination the site's footer does include links and encouragement to file an issue:

![join-page-footer](https://cloud.githubusercontent.com/assets/1244599/11885107/837059b2-a4d3-11e5-9375-1faace8c8981.png)

Does that suffice? Other ideas welcome.

**Comment by afeld** [comment]
Yep, thanks!
