### ISSUE TITLE
Give applicants a heads-up about implications of becoming a fed

### ISSUE THREAD

**Issue by fureigh** [18F/joining-18f#68]
**User story:**
As an applicant who may not have previously worked in government, I want to understand the personal implications of becoming an employee of the federal government (e.g., the Hatch Act, FOIAability of _____, social media considerations, implications for attending or speaking at conferences, etc.) so that I can make an informed decision about whether to accept an employment offer.

**Current behavior:**
The site includes [some information about conferences](https://pages.18f.gov/joining-18f/conferences-training-travel/). The site includes no information about legal ramifications of being a federal employee.

**Desired behavior:**
See above. Exact content TBD.

**Technical notes:**
N/A

**Outstanding questions:**
- What will it say? :)

**Comment by fureigh** [comment]
@brittag, want to take a shot at the content aspect of this?

**Comment by melodykramer** [comment]
@fureigh We have much of this material collected as part of the new hires training. I just posted the link to the Hatch Act / FOIA / ethics guide in #newcomers - we should have the conference info by the end of this week, after the session related to that.

**Comment by fureigh** [comment]
@melodykramer Thanks! Looking forward to incorporating.

**Comment by fureigh** [comment]
- Privacy Act

**Comment by brittag** [comment]
I'd suggest also including in this resource for prospective applicants:
- [Standards of Ethical Conduct for Employees of the Executive Branch](https://www.oge.gov/Web/oge.nsf/Resources/Standards+of+Ethical+Conduct+for+Employees+of+the+Executive+Branch)
- [GSA Social Media Policy](http://www.gsa.gov/portal/content/180607)

**Comment by coreycaitlin** [comment]
Given the current pace of communications and the complexity of the relevant guidance, I think this is a conversation best had later in the application process — and possibly in-person.

If this seems worth reopening, please create an issue either in the [18F Handbook repo](https://github.com/18F/handbook) or in the [18F site repo](https://github.com/18F/18f.gsa.gov).
