### ISSUE TITLE
Make it mandatory to select functional skill

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/joining-18f#74]
We need to make the following additions to the application page and make them mandatory:

Functional Skills - drop down with the following options:
Acquisition/Contracts Management
Data Visualization
Dev Ops
Design: Visual
Design: Content
Design: Front End
Design: User Exp. & Research
Marketing, Communications
Operations, Recruiting
Product Management
Project Management
Software Dev: Front End
Software Dev: Back End
Software Dev: DevOps
Technical Architecture

General Schedule - Grade Levels drop down with 13,14, 15 options
18F hires against GSA position descriptions at the GS 13, GS 14 and GS 15 level. Please select the level that you would wish to apply to. For more information, please read here
Innovation Specialist - Grade 13
Innovation Specialist - Grade 14
Innovation Specialist - Grade 15

Team Talent is working on the "please read here" section. :)

**Comment by fureigh** [comment]
@jamiealbrecht: I updated the "Primary skillset" field. Two questions about it:
- Do you want the field name to change to "Functional skills?"
- If so, should applicants be able to select more than one?

**Comment by fureigh** [comment]
Per conversation with @rooneywp, sounds like the "Primary skillset" field with the supplementary "Other skills you have" field is consistent with the current process. We can iterate in the future as appropriate.

As the GS level question will require some more discussion before implementing, I'll break it into a new issue.
