### ISSUE TITLE
Update content to reflect new process

### ISSUE THREAD

**Issue by fureigh** [18F/joining-18f#75]
As a prospective applicant, I want to understand what timelines to expect, what kind of cohort-level application analysis to expect, etc., so I can assess my progress accordingly.

**Comment by fureigh** [comment]
More information needed. For now, this is a placeholder.

**Comment by coreycaitlin** [comment]
We resolved the inaccuracies by streamlining this content in the move to the [18F site](https://18f.gsa.gov/join/#the-interview-process). We don't have predictable timelines for hiring, and cohort-level guidance will be included in individual postings. Closing for now!
