### ISSUE TITLE
Draft GS selection narrative/guide

### ISSUE THREAD

**Issue by fureigh** [18F/joining-18f#77]
Toward #76. :)

**Comment by pixelwake** [comment]
https://docs.google.com/document/d/1V9mVCsDFrGwVjDPoLlx5BPkH2u9mIlcCU72m_HTCSRM/edit

Analysis and draft language for MVP narrative guide.

**Comment by pixelwake** [comment]
New updates to proposed language for the MVP for guidance on selecting a GS grade. This hasn't been proofed/edited, looking to get feedback.

https://docs.google.com/document/d/1V9mVCsDFrGwVjDPoLlx5BPkH2u9mIlcCU72m_HTCSRM/edit

Two options for how we display the information to the user. Table and bullet list.

**Comment by fureigh** [comment]
Looking good! The table display is much clearer. I went ahead and made some copy edits in #98. Let me know what you think.

There may be room to make the salary/locality part clearer... what would you think of including sample numbers for SF and DC [and perhaps others]? I'm trying to avoid people in places with significant locality pay closing the tab because they don't realize at a glance that the numbers shown are much lower than the compensation they'd actually get.

(ccing @brittag in case she has feedback)

**Comment by fureigh** [comment]
Thanks for adding those sample numbers, @rooneywp. Closing this issue.
