### ISSUE TITLE
Update Join Page Content

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/joining-18f#79]
Right now this is a placeholder to remind me to update all of the sections of the join page. Tagging @cbrydges on this too.

**Comment by jamiealbrecht** [comment]
add update on the transition process to here:  page https://pages.18f.gov/joining-18f/

Our call for talented, civic-minded folks to join 18F has been answered loudly, clearly, and in high numbers. To better handle this influx of applications and to better serve the entire 18F team, we’re embarking on an evaluation of our talent selection process. Like the rest of the products built at 18F, this process demands iterating too. 

We’re currently re-engineering major parts of our talent selection process. Our goal: to deliver an improved application, interview, and hiring experience.

If you’re interested in joining our team, please check back in mid November for a list of open positions, our new application form, and updated content on our new process and projected hiring timelines.

In the meantime, if you want to hear about the latest @18F, please follow us on Twitter, sign up for our newsletter, and check out our work on GitHub. 

If you have applied to 18F recently, we want to apologize for our slow response time. We haven’t forgotten you — thank you sincerely for your patience. You will receive an email by Friday, November 6 from our Talent Team with an update on your application and next steps.

If you have any questions, please reach our Talent Team at join18f@gsa.gov 

Then the rest of the pages need to say something like “this is a work in progress and we’ll have details about <page subject> up when we can. Questions email Talent Team @ join18f@gsa.gov or something...

**Comment by fureigh** [comment]
Took a big first pass at this in #81 and #83.

**Comment by jamiealbrecht** [comment]
closing this issue. for now, during the transition phase, the content is as up to date as possible. there will be new, specific updates to come later.
