### ISSUE TITLE
Join 18F Application: Change Vet Preference Question

### ISSUE THREAD

**Issue by pixelwake** [18F/joining-18f#89]
To better facilitate the manual processing of applications.

Change the vet preference question to be:
"Are you a Veteran of the U.S. Armed Forces or are you eligible for "derived" preference?"

Possible answers:
"Yes"
"No"

Note: 18F is not responsible for determining if a candidate is eligible for preference, that is part of the responsibility of OHRM during the certification process. 18F can facilitate by capturing the information on the application.

**Comment by fureigh** [comment]
@rooneywp Doublechecking: we no longer need to capture points, just a yes/no?

**Comment by pixelwake** [comment]
@fureigh Just saw that there is a Joining 18f app repo, ooops. Do you want me to move these issues over there?

Re: points - We do not need to capture the points or their specific level of preference since we aren't actually applying the preference ourselves. Also the qualification method we are using preference is applied using points.

**Comment by fureigh** [comment]
@rooneywp Nope, this is the perfect place for these issues, though that's a good reminder to update both projects' READMEs to clarify their relationship. (The other repo is for the Flask app that's been put on hold.)

Thanks for the clarification re: points. Updated in the Google form.
