### ISSUE TITLE
Join 18F Application: Update "Where did you learn about 18F" question

### ISSUE THREAD

**Issue by pixelwake** [18F/joining-18f#90]
Change: Add language to the description that indicates clearly that if they were referred by an individual, this is the field to document this information.

**Comment by fureigh** [comment]
@rooneywp How about: "Where did you learn about 18F? If someone referred you to us, please include their name."

**Comment by pixelwake** [comment]
@fureigh That works for me!

**Comment by fureigh** [comment]
@rooneywp Right-o. I'll make that change.
