### ISSUE TITLE
Join 18F Application: Modify Functional Skills ("Primary Skill") section

### ISSUE THREAD

**Issue by pixelwake** [18F/joining-18f#91]
Current state: Applicant selects a primary skill from a drop down list.

To capture a better representation of the candidate and enable more dynamic routing to SMEs and team, add the ability to indicate self assessment of multiple skill areas

Notes:
There are two options that we are considering that meet the requirements (see below). The preferred solution is something that is closest to the first option (also used by PIF). Would love thoughts/feedback if there is a better way to do it.

1 - A drop down per functional skill with a 0-5 rating.
- Greatest flexibility in allocation
- Greatest degrees of assessment, more information about candidate (Candidate can indicate multiple top skills, Candidate also indicates which skills they don't have)
- Potentially sub-optimal applicant experience due to increased number of fields to complete (15 fields)
- Does not force applicant to rank skills

![option 1](https://cloud.githubusercontent.com/assets/13383307/11047034/5651c724-86e5-11e5-915f-0b988e8f8ee3.png)

2 - A drop down for top skills in order of expertise (1st, 2nd, 3rd)
- Better user experience with only three fields to complete
- Forces stack ranking of top 3 skills
- Decreased level of flexibility in allocation
- Decreased degrees of assessment, less information about candidate

![option 2](https://cloud.githubusercontent.com/assets/13383307/11047060/7428d5f8-86e5-11e5-98b8-3586dd49e00c.png)

**Comment by pixelwake** [comment]
Here is the final list of Functional Skills

Acquisition, Contracts
Business Development
Communications, Marketing
Consulting
Cybersecurity
Design: Visual
Design: Content
Design: Front End
Design: UX, Research
Operations, Recruiting
Product Management
Project Management
Software Dev: Front End
Software Dev: Back End
Software Dev: DevOps, SRE

**Comment by fureigh** [comment]
@rooneywp I updated the list of skills to match the above.

Of the presentation options, I lean toward the second because completing 15 fields is arduous... anyone else listening want to weigh in or do a hallway usability test?

**Comment by fureigh** [comment]
@rooneywp Ready for review.

**Comment by pixelwake** [comment]
@fureigh One last request on this, can we make the 2nd and 3rd skill's required? I know it's not ideal for UX but we may need that data to justify how the applicants are being routed to the SMEs during qualification.

After that :+1:

**Comment by fureigh** [comment]
@rooneywp I'm :+1: to being able to justify applicant routing, but what's someone supposed to do if only one of the skillsets applies to them? I think we risk getting false (and more confusing) data if we require the second and third.

**Comment by pixelwake** [comment]
@fureigh Good point. Let's go with it as is. This will could be a good experiment that will provide data as we review option 1.

**Comment by fureigh** [comment]
@rooneywp :+1: 

(Future metrics include thumbs-ups per hour. :) )
