### ISSUE TITLE
Join 18F Application: Update order of questions

### ISSUE THREAD

**Issue by pixelwake** [18F/joining-18f#93]
This issue can be done once the final changes to the application have been made.

To better facilitate the manual processing required per applicant, reorder the questions within the application

New Order:
Name
Email
Phone
City
State
ZIP Code
Vet Preference
Additional Opportunities
Eligibility
Availability
Preferred location
Where did you learn about 18F? (Add something that says enter referral information here)
What position would you like to apply to? (Grade Level)
Functional Skills (Drop Downs)
Other Skills (Short Answer Text)
Link 1
Link 2
Link 3 
Resume Link
Resume
Why do you want to join 18F?
What role at 18F most excites you and that you believe you are the best fit for and why? (This question still in development)

**Comment by pixelwake** [comment]
Here is the final list of Functional Skills

Acquisition, Contracts
Business Development
Communications, Marketing
Consulting
Cybersecurity
Design: Visual
Design: Content
Design: Front End
Design: UX, Research
Operations, Recruiting
Product Management
Project Management
Software Dev: Front End
Software Dev: Back End
Software Dev: DevOps, SRE

**Comment by fureigh** [comment]
:+1:

**Comment by fureigh** [comment]
@rooneywp Just confirming: this overrides previous skill lists that included things like data visualization, yes?

**Comment by fureigh** [comment]
I'll keep the 'citizenship' field (checkbox) above vet preference.

**Comment by fureigh** [comment]
Whoops — just saw that it's accounted for above as "eligibility." Disregard my last comment.

**Comment by pixelwake** [comment]
@fureigh Re:Functional Skills Yes, this replaces the existing list. Also, realized that I included that comment on the wrong issue. I copied it to #91

**Comment by fureigh** [comment]
@rooneywp :+1: Thanks for copying to #91.

About the first part: is the question "What role at 18F most excites you and that you believe you are the best fit for and why?" still in development? I'd suggest "What role at 18F do you believe you're the best fit for and why?" — with or without the "and why."

**Comment by pixelwake** [comment]
@fureigh I actually created a separate issue #101 for that essay question. (Definitely want to retro with you after this to get your thoughts on github best practices).

I like "What role at 18F do you believe you're the best fit for and why?"

I like the " and why". I think it does a good job prompting the applicant for more than just listing the role.

**Comment by fureigh** [comment]
@rooneywp Right-o. Added the Q to the application.

**Comment by fureigh** [comment]
(I'm currently implementing as stated above, but for future reference, the order of questions that we present to the applicants is separable from the order of questions in the results spreadsheet.)

**Comment by pixelwake** [comment]
@fureigh Good to know! That will certainly make things easier for next time.

**Comment by fureigh** [comment]
@rooneywp The [Google form version](https://docs.google.com/forms/d/1OCtPVLMP8O5nfDnGTJZngxFxZR4EvFcYSqJ-thHxojc/viewform?usp=send_form) of this is ready for review. Take a look and let me know whether it's good to go. (I took a stab at #101 too.)

**Comment by pixelwake** [comment]
@fureigh Can we change the values in the drop down for "What position (grade level) are you applying to?" to be:

Innovation Specialist (Grade 13)
Innovation Specialist (Grade 14)
Innovation Specialist (Grade 15)

I know it's bulky but it will keep us in closer compliance with HR.

**Comment by fureigh** [comment]
@rooneywp Yep! Anything else or are we ready for @xtine to work her magic?

**Comment by fureigh** [comment]
(I changed it to the even bulkier, but consistent with the no-'grade'-left-without-its-'level', 'Innovation Specialist (Grade Level 13)', etc.)

**Comment by pixelwake** [comment]
@fureigh Looks good. The last thing for the app looks the Functional Skills section #91

**Comment by fureigh** [comment]
@rooneywp Ah, yes. I'll implement option 2 for now; we can always iterate on it.

**Comment by pixelwake** [comment]
:+1:

**Comment by fureigh** [comment]
@rooneywp Ready for another look.

**Comment by pixelwake** [comment]
:+1:
