### ISSUE TITLE
Join 18F Application: Remove the auto sort from response sheet

### ISSUE THREAD

**Issue by pixelwake** [18F/joining-18f#97]
Change: To facilitate the manual processing activities, remove the auto sort function from the application response sheet.

Notes: The vet auto sort is no longer necessary since all candidates will go through qualification and OHRM will review all for Vet status and apply accordingly.

**Comment by fureigh** [comment]
@rooneywp Roger. If it's no longer to autosort by veteran status (even yes/no), the responses will be automatically sorted in reverse chronological order. Please confirm that that's the desired result.

**Comment by pixelwake** [comment]
@fureigh Reverse chronological is fine.

**Comment by fureigh** [comment]
@rooneywp Done. [Take a look](https://docs.google.com/spreadsheets/d/1mgwSBbgNfHzxp-goq-zlAv3lSlfVCOB8NmbKq1FoEiY/edit#gid=1220387769) and if it looks good to you, close this issue.

**Comment by pixelwake** [comment]
:+1:
