### ISSUE TITLE
Who We Are Hiring: Add updated roles

### ISSUE THREAD

**Issue by pixelwake** [18F/joining-18f#99]
We need a way to house the different roles that we are currently hiring for so that applicants can see if there is something they are specifically interested in and that they can use during the application process to indicate that interest.

Potential solutions
MVP: Use the current Who We Are Hiring page and add the positions with a short blurb about each.

Long term: Create a new page that is used to only house the roles. Contains a description of each team with links to the performance profiles associated with role.

Notes: I'll create a pull request for the MVP solution.

**Comment by fureigh** [comment]
@rooneywp FYI: we took down the longer position descriptions while the new process was being worked out, but they're still available at https://github.com/18F/joining-18f/tree/18f-pages/_positions and could easily be reintegrated.

**Comment by fureigh** [comment]
MVP was closed in #99; leaving this issue open for the longer-term version.

**Comment by pixelwake** [comment]
@fureigh Ok great, I wasn't sure how much work it would be to bring those back online. What about creating a separate page? Does it require more than adding the file in the repo?

The next item is for me to collect updated Profiles for all the roles.

**Comment by meiqimichelle** [comment]
( /cc @meiqimichelle for anything re: front end designer position )

**Comment by pixelwake** [comment]
@fureigh Can you create a new page just for the roles? Once we have that I up I can start populating it with the copy and links.

**Comment by pixelwake** [comment]
@fureigh Disregard the previous comment. Instead of creating a new page I think we can just rearrange the information and use the existing who we are hiring to house the role info. Submitted PR's for the initial move #126  #123

**Comment by pixelwake** [comment]
Closing this issue. MVP was ready for launch and new page has been created. Ongoing changes captured in #124
